name: Convert to Qiita articles

on:
  push:
    branches:
      - main
    paths:
      - 'articles/**/*.md'
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  convert_articles_to_qiita:
    runs-on: ubuntu-slim
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          ssh-key: ${{ secrets.DEPLOY_KEY }}

      - name: Convert to Qiita articles
        uses: yuzolabs/zenn-qiita-converter@v0.1.0
        with:
          convert-commit-message: "🔄 auto: synchronize qiita articles"
